### ISSUE TITLE
Implement my account page

### ISSUE THREAD

**Issue by c-nguyen** [WebServiceIO/BookTradeSite#4]
Users need a my account button to bring them to a page that displays all the books they're selling

**Comment by c-nguyen** [comment]
Uploaded a template. Need to make it responsive and add a submit/save button

**Comment by TannerS** [comment]
We need to add a button so that user can save changes to account info, but the trickier part is how to make the box display info, then a simply button can edit each field OR we can make it so one click takes you to an entire new page where you can make your edits. whichever is easier for now, lets do that 👍

**Comment by c-nguyen** [comment]
It depends on you. Both are easy front-end wise. What do you want to do?

**Comment by TannerS** [comment]
update?

**Comment by c-nguyen** [comment]
finished account page design along with pages for changing username, password, and contact information.
the only page missing is the view all books page

**Comment by c-nguyen** [comment]
view all books page is added
